language: java
dist: bionic
jdk:
  - oraclejdk8
  - openjdk11
git:
  submodules: false
before_install:
  - git config --global user.email "travis-ci@travis-ci.com"
  - git config --global user.name "Travis CI"
install:
  - ./paper patch
script:
  - shellcheck --color=always --exclude 2001 --external-sources scripts/*.sh
cache:
  directories:
    - '$HOME/.m2/repository'
    - 'work/Minecraft'
